workflows:
  ios-workflow:
    name: ios_workflow
    environment:
      groups:
        - app_store_credentials # <-- (Includes APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY)
        - certificate_credentials # <-- (Includes CERTIFICATE_PRIVATE_KEY)
        - other
       # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
      vars:
        XCODE_PROJECT: "PTPlayer.xcodeproj"  # PUT YOUR WORKSPACE NAME HERE
        XCODE_SCHEME: "PTPlayer" # PUT THE NAME OF YOUR SCHEME HERE
        BUNDLE_ID: "com.apolloplanet.superbee"
        APP_STORE_CONNECT_PRIVATE_KEY: "MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgOzdH13jHu0j+OsN8pmwB3PU8ftIlLwTaWpibi7YYrIugCgYIKoZIzj0DAQehRANCAAQB9AgJnQ0nwCo2tK0n8njvquN05rP7Ryc3Yr64ttySiuzu2veF1tylFhSUVt6C+MlwQ5mWzo4uIineDIDSx2mU"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "S987ULB824"
        APP_STORE_CONNECT_ISSUER_ID: "14b88b2d-03aa-479c-b6d7-8782ce801319"
        APP_STORE_APP_ID: "1594596994"

      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        script: keychain initialize
      - name: Fetch signing files
        script: app-store-connect fetch-signing-files --type IOS_APP_STORE --create com.apolloplanet.superbee
      - name: Add certificates to keychain
        script: keychain add-certificates 
      - name: Increment build number
        script: agvtool new-version -all $(($BUILD_NUMBER +1))
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for distribution
        script: xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY      # Contents of the API key
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER    # Alphanumeric value that identifies the API key
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID      # Alphanumeric value that identifies who created the API key
        submit_to_testflight: false        # Optional boolean, defaults to false. Whether or not to submit the uploaded build to TestFlight to automatically enroll your build to beta testers.
        #apple_id: $APPLE_ID_EMAIL
        #password: $APP_SPECIFIC_PASSWORD
      # beta_groups:                                  # Specify the names of beta tester groups that will get access to the build once it has passed beta review. 
      #     - group name 1
      #     - group name 2